databaseChangeLog:
  - logicalFilePath: path_independent
  - include:
      file: database/seeds/seed.yaml
  - include:
      file: database/datasets/seed-data.yaml
  - include:
      file: database/changes/0001.create_table_events.yaml
  - include:
      file: database/changes/0002.create_table_categories.yaml
  - include:
      file: database/changes/0003.create_table_schedules.yaml
  - include:
      file: database/changes/0004.create_table_organizers.yaml
  - include:
      file: database/changes/0005.create_table_addresses.yaml
  - include:
      file: database/changes/0006.create_table_passwordresets.yaml
