databaseChangeLog:
    - logicalFilePath: path_independent
    - include:
        file: database/seeds/seed.yaml
    - include:
        file: database/datasets/seed-data.yaml
    - include:
        file: database/changes/0001.create_table_event.yaml
    - include:
        file: database/changes/0002.create_table_category.yaml
    - include:
        file: database/changes/0003.create_table_schedule.yaml     
    - include:
        file: database/changes/0004.create_table_organizer.yaml  
    - include:
        file: database/changes/0005.create_table_address.yaml
    - include:
        file: database/changes/0006.create_table_passwordreset.yaml
